<a href="https://colab.research.google.com/github/Hk05101/Cognitive-Computing/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.array([2,4,6,8,10])
print("Original array answer -",arr)
print("after adding 2 answer -",arr+2)
print("after multiplying 3 answer - ",arr*3)
print("after dividing with 2 answer -",arr/2)

Original array answer - [ 2  4  6  8 10]
after adding 2 answer - [ 4  6  8 10 12]
after multiplying 3 answer -  [ 6 12 18 24 30]
after dividing with 2 answer - [1. 2. 3. 4. 5.]


In [2]:
import numpy as np

nums = np.array([1, 2, 3, 6, 4, 5])
print("(a) Reversed array:", np.flip(nums))
print("\n")
arr1 = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
arr2 = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
print("(b) First list of numbers:", arr1)
freq = np.bincount(arr1)
print("Occurrences of each number (0 to 5):", freq)
max_freq_num = np.argmax(freq)
print("Number with the highest occurrence:", max_freq_num)
pos = np.where(arr1 == max_freq_num)[0]
print("Indexes where", max_freq_num, "appears:", pos)
print("\n")
print("Second list of numbers:", arr2)
freq2 = np.bincount(arr2)
print("Occurrences of each number (0 to 4):", freq2)
max_freq_num2 = np.argmax(freq)
print("Number with the highest occurrence in second list:", max_freq_num2)
pos2 = np.where(arr2 == max_freq_num2)[0]
print("Indexes where", max_freq_num2, "appears:", pos2)

(a) Reversed array: [5 4 6 3 2 1]


(b) First list of numbers: [1 2 3 4 5 1 2 1 1 1]
Occurrences of each number (0 to 5): [0 5 2 1 1 1]
Number with the highest occurrence: 1
Indexes where 1 appears: [0 5 7 8 9]


Second list of numbers: [1 1 1 2 3 4 2 4 3 3]
Occurrences of each number (0 to 4): [0 3 2 3 2]
Number with the highest occurrence in second list: 1
Indexes where 1 appears: [0 1 2]


In [3]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print("Element at first row and second column:",arr[0,1])
print("Element at third row and first column:",arr[2,0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at first row and second column: 20
Element at third row and first column: 70


In [4]:
import numpy as np
noor=np.linspace(10,100,25)
print("The array is:",noor)
print("Dimensions of array:",noor.ndim)
print("Shape of array:",noor.shape)
print("Size of array:",noor.size)
print("Data-type of elements:",noor.dtype)
print("Total bytes consumed:",noor.nbytes)
transpose=noor.reshape(25,1)
print("Transpose of array:",transpose)
transpose_T=noor.T
print("Transpose using T attribute:",transpose_T)
print("Does transpose and transpose_T give same result?",np.array_equal(transpose,transpose_T))

The array is: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of array: 1
Shape of array: (25,)
Size of array: 25
Data-type of elements: float64
Total bytes consumed: 200
Transpose of array: [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Does transpose and transpose_T give same result? False


In [5]:
import numpy as np
ucs420_noor=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("The array is:",ucs420_noor)
print("Mean of elements:",np.mean(ucs420_noor))
print("Median of elements:",np.median(ucs420_noor))
print("Maximum element is:",np.max(ucs420_noor))
print("Minimum element is:",np.min(ucs420_noor))
print("Unique element is:",np.unique(ucs420_noor))
reshaped_ucs420_noor=ucs420_noor.reshape(4,3)
print("Reshaped array:",reshaped_ucs420_noor)
resized_ucs420_noor=np.resize(ucs420_noor,(2,3))
print("Resized array:",resized_ucs420_noor)

The array is: [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean of elements: 43.333333333333336
Median of elements: 37.5
Maximum element is: 90
Minimum element is: 10
Unique element is: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array: [[10 20 30]
 [40 50 60]]
